"""changed column name

Revision ID: 4d06233a0aa3
Revises: ccbf3dbea0b7
Create Date: 2025-02-26 11:04:43.006718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d06233a0aa3'
down_revision: Union[str, None] = 'ccbf3dbea0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
