"""added first name to order model

Revision ID: ac3a0bf57213
Revises: b86425fe3314
Create Date: 2025-03-11 11:05:37.338725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3a0bf57213'
down_revision: Union[str, None] = 'b86425fe3314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('first_name', sa.String(length=256), nullable=True))
    op.add_column('orders', sa.Column('last_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    # ### end Alembic commands ###
