"""added some columns to order table

Revision ID: b86425fe3314
Revises: e8503d5d8bad
Create Date: 2025-03-07 22:27:12.741589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86425fe3314'
down_revision: Union[str, None] = 'e8503d5d8bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('location', sa.String(length=256), nullable=True))
    op.add_column('orders', sa.Column('phone_number', sa.String(length=256), nullable=True))
    op.add_column('orders', sa.Column('street', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'street')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'location')
    # ### end Alembic commands ###
