"""removed the unique constraint

Revision ID: e8503d5d8bad
Revises: 061e5a4b0145
Create Date: 2025-03-05 11:10:18.219869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8503d5d8bad'
down_revision: Union[str, None] = '061e5a4b0145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subcategories_name_key', 'subcategories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subcategories_name_key', 'subcategories', ['name'])
    # ### end Alembic commands ###
